# Site settings
title: PyLadiesBRConf
description: Encontro Nacional de PyLadies de todo o Brasil
baseurl: "/conf-1" # the subpath of your site, e.g. /blog
url: "https://brasil.pyladies.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: PyLadiesBRConf
user_description: A PyLadies BR Conf é uma conferência de PyLadies para PyLadies. O PyLadies é um grupo internacional, mantido pela Python Software Foundation. Nossa missão é ajudar mais mulheres a tornarem-se membros ativos da comunidade Python. Queremos reunir mulheres que possam inspirar e renovar quem está entrando ou há algum tempo na área tecnológica. Esta será nossa primeira edição do evento, que irá ocorrer em Natal no dia 16 de outubro.
user_title: 1ª Conferência PyLadies do Brasil
email: brazil@pyladies.com
twitter_username: pyladiesbrazil
github_username:  pyladies-brazil
gplus_username:  https://plus.google.com/114419825361109783805

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules', 'gulpfile.js', 'LICENSE.txt',  'particle.jpg', 'README.md', 'README.txt', 'yarn.lock']
